project:
  type: website
website:
  title: "Ivann's blog"
  navbar:
    right:
      # - about.qmd
      - icon: github
        href: https://github.com/ischlo
        # target: _blank
      - icon: twitter
        href: https://twitter.com/irscars
        # target: _blank
      
format:
  html:
    theme: 
      - simplex
      - styles.scss
    # mainfont: 'Courier New'
execute:
  freeze: auto
editor: visual

